[phases.setup]
nixPkgs = ["python39"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "streamlit run frontend/app_direct_input.py --server.port=$PORT --server.address=0.0.0.0"